// <auto-generated />
namespace Registration.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class professoridea : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(professoridea));
        
        string IMigrationMetadata.Id
        {
            get { return "201804061136371_professoridea"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
