// <auto-generated />
namespace Registration.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class class1force : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(class1force));
        
        string IMigrationMetadata.Id
        {
            get { return "201804081142346_class1-force"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
